keys:
  - &netbook age1ucyn5dpf0mmzef2vd8ktmh3d8cmywuvdcdt6qtjsplmnx7k0ccts8796hr
  # - &uconsole age19xdn8e66zzf2lmwzwlxnuu3uqxxmj9chxhms2slydvra9uczzf5qgvw973

  # - &users:
  #   - &craft age1tz97dum6dadchmqkaax50qfcyk35dhzjkt0tsa9fpjmrltvlyqls0u0atm
  # - &hosts:
  #   - &netbook age1z4ne5whkl62d8qy8xhfj96fgxlyelqld2qzm9jk70lxpnmpvpv7qhxhvc7
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        # - *craft
        - *netbook
