# key:
#   - &netbook age1yasm3t9fuufm72eytdg4jjrv55syu8tjcdtwv8qcg758fg7p0p3qxwpne4
#   - &uconsole age19xdn8e66zzf2lmwzwlxnuu3uqxxmj9chxhms2slydvra9uczzf5qgvw973
#   - &old-laptop age10307wulde2n4h3nn98rqtgsn7q0rmutstl4mv3umwx7jzeuwjsvq0uzddz

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - &netbook age1yasm3t9fuufm72eytdg4jjrv55syu8tjcdtwv8qcg758fg7p0p3qxwpne4
        - &uconsole age19xdn8e66zzf2lmwzwlxnuu3uqxxmj9chxhms2slydvra9uczzf5qgvw973
        - &old-laptop age10307wulde2n4h3nn98rqtgsn7q0rmutstl4mv3umwx7jzeuwjsvq0uzddz
