keys:
  - &netbook age1ucyn5dpf0mmzef2vd8ktmh3d8cmywuvdcdt6qtjsplmnx7k0ccts8796hr
  - &uconsole age1fqf5mc3zhazxp5f5xmznahze6xp65m5g7vwvq0yjdqlh83memvrqfsgc9t

  # - &users:
  #   - &craft age1tz97dum6dadchmqkaax50qfcyk35dhzjkt0tsa9fpjmrltvlyqls0u0atm
  # - &hosts:
  #   - &netbook age1z4ne5whkl62d8qy8xhfj96fgxlyelqld2qzm9jk70lxpnmpvpv7qhxhvc7
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *uconsole
        - *netbook
